language: node_js
node_js:
- '6.10'
install:
- npm config set registry http://registry.npmjs.org/
- npm install --no-optional
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  on: 
    tags: true
  email : rafal@openmrs.org
  api_key:
    secure: $NPM_API_KEY
